### ISSUE TITLE
Docs: Provide an example of useRoute() with vue frouter 4.x to access route params

### ISSUE THREAD

**Issue by natemate90** [testing-library/vue-testing-library#252]
I'm trying to mock the vue-router useRoute() function.

Test should pass as I mock useRoute inside vue-router, but instead the test fails:

```
 FAIL  src/components/base/sidebar/SidebarMenu.spec.ts (9.592 s)
  ● Console

    console.warn
      [Vue warn]: injection "Symbol([vue-router]: route location)" not found.
        at <Anonymous ref="VTU_COMPONENT" >
        at <VTUROOT>

      22 | import { useRoute } from 'vue-router'
      23 |
    > 24 | const route = useRoute()
         |               ^
      25 |
      26 | const { helplinks, navigation } = useSidebarLinks(route)
      27 | </script>

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6800:17)
      at Object.inject (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1508:13)
      at Object.useRoute (node_modules/vue-router/dist/vue-router.cjs.js:3406:16)
      at setup (src/components/base/sidebar/SidebarMenu.vue:24:15)
      at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6917:22)
      at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6535:29)
      at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6491:11)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4369:13)

    console.warn
      [Vue warn]: Unhandled error during execution of setup function
        at <Anonymous ref="VTU_COMPONENT" >
        at <VTUROOT>

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6800:17)
      at logError (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6974:9)
      at handleError (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6966:5)
      at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6920:9)
      at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6535:29)
      at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6491:11)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4369:13)
      at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4344:17)


```

**Related information:**

- `@testing-library/vue` version:
- `Vue` version: 3.2.2
- `node` version: 16.5.0
- `npm` (or `yarn`) version: 7.19.1

Relevant code or config (if any)

```javascript

beforeEach(() => {
  jest.mock('vue-router', () => ({
    useRoute: () => ({
      params: {
        locale: 'en',
        id: '123abc'
      }
    })
  }))
})

```

**Additional context**

**Comment by sand4rt** [comment]
@natemate90 you can find an example [here](https://github.com/testing-library/vue-testing-library/blob/main/src/__tests__/vue-router.js):
